require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BlsController do

  # This should return the minimal set of attributes required to create a valid
  # Bl. As you add validations to Bl, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BlsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all bls as @bls" do
      bl = Bl.create! valid_attributes
      get :index, {}, valid_session
      assigns(:bls).should eq([bl])
    end
  end

  describe "GET show" do
    it "assigns the requested bl as @bl" do
      bl = Bl.create! valid_attributes
      get :show, {:id => bl.to_param}, valid_session
      assigns(:bl).should eq(bl)
    end
  end

  describe "GET new" do
    it "assigns a new bl as @bl" do
      get :new, {}, valid_session
      assigns(:bl).should be_a_new(Bl)
    end
  end

  describe "GET edit" do
    it "assigns the requested bl as @bl" do
      bl = Bl.create! valid_attributes
      get :edit, {:id => bl.to_param}, valid_session
      assigns(:bl).should eq(bl)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Bl" do
        expect {
          post :create, {:bl => valid_attributes}, valid_session
        }.to change(Bl, :count).by(1)
      end

      it "assigns a newly created bl as @bl" do
        post :create, {:bl => valid_attributes}, valid_session
        assigns(:bl).should be_a(Bl)
        assigns(:bl).should be_persisted
      end

      it "redirects to the created bl" do
        post :create, {:bl => valid_attributes}, valid_session
        response.should redirect_to(Bl.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bl as @bl" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bl.any_instance.stub(:save).and_return(false)
        post :create, {:bl => { "user_id" => "invalid value" }}, valid_session
        assigns(:bl).should be_a_new(Bl)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bl.any_instance.stub(:save).and_return(false)
        post :create, {:bl => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bl" do
        bl = Bl.create! valid_attributes
        # Assuming there are no other bls in the database, this
        # specifies that the Bl created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Bl.any_instance.should_receive(:update_attributes).with({ "user_id" => "1" })
        put :update, {:id => bl.to_param, :bl => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested bl as @bl" do
        bl = Bl.create! valid_attributes
        put :update, {:id => bl.to_param, :bl => valid_attributes}, valid_session
        assigns(:bl).should eq(bl)
      end

      it "redirects to the bl" do
        bl = Bl.create! valid_attributes
        put :update, {:id => bl.to_param, :bl => valid_attributes}, valid_session
        response.should redirect_to(bl)
      end
    end

    describe "with invalid params" do
      it "assigns the bl as @bl" do
        bl = Bl.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bl.any_instance.stub(:save).and_return(false)
        put :update, {:id => bl.to_param, :bl => { "user_id" => "invalid value" }}, valid_session
        assigns(:bl).should eq(bl)
      end

      it "re-renders the 'edit' template" do
        bl = Bl.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bl.any_instance.stub(:save).and_return(false)
        put :update, {:id => bl.to_param, :bl => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bl" do
      bl = Bl.create! valid_attributes
      expect {
        delete :destroy, {:id => bl.to_param}, valid_session
      }.to change(Bl, :count).by(-1)
    end

    it "redirects to the bls list" do
      bl = Bl.create! valid_attributes
      delete :destroy, {:id => bl.to_param}, valid_session
      response.should redirect_to(bls_url)
    end
  end

end
